version: '3.1'
services:
  stats-server:
    build: ./ewm-stats/service
    image: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_statsDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_statsDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#
#  ewm-service:
#    build: ./ewm-main
#    image: ewm-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#    environment:
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/ewmDB
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#
#  ewm-db:
#    image: postgres:16.1
#    container_name: ewm-db
#    ports:
#      - "6542:5433"
#    environment:
#      - POSTGRES_DB=ewmDB
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root